on:
  release:
    types:
      - published

name: release

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: deps
        run: python -m pip install -U build

      - name: build
        run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
