name: tox
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  schedule:
    - cron: "0 8 * * 0"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: tox -e ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - "3.13"
          - "3.12"
          - "type"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Tox tests
        id: test
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
